frontend:
  build: ./frontend/
  dockerfile: Dockerfile
  links:
      - backend
  ports:
      - "8080:2015"
  volumes:
      - ./frontend:/site/

backend:
  build: ./backend/
  dockerfile: Dockerfile
  links:
      - db
  volumes:
      - ./backend:/go/src/github.com/guilhermebr/backenderia/backend

mongodata:  
  image: mongo
  volumes:
        - /data/db
  command: --break-mongo

db:
  image: mongo
  volumes_from:
          - mongodata
  ports:
        - "27017"
  restart: always
